<a href="https://colab.research.google.com/github/cypherkrish/Machine-Learning-Basics/blob/main/01_03_Linerar_Regression_Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/Machine-Learning-Basics/main/Data/Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [5]:
X = df.drop('sales', axis = 1)

In [6]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [7]:
y = df['sales']

In [8]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [9]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
ploynomial_converters = PolynomialFeatures(degree = 3, include_bias = False)

In [11]:
ploy_features = ploynomial_converters.fit_transform(X)

In [12]:
ploy_features.shape

(200, 19)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(ploy_features, y, test_size=0.33, random_state=42)

In [15]:
X_train.shape

(134, 19)

In [16]:
from sklearn.preprocessing import  StandardScaler

In [17]:
scalar = StandardScaler()

In [18]:
scalar.fit(X_train)

StandardScaler()

In [19]:
X_train_scaled = scalar.transform(X_train)

In [20]:
X_test_scaled = scalar.transform(X_test)

In [21]:
X_train[0]

array([2.93600000e+02, 2.77000000e+01, 1.80000000e+00, 8.62009600e+04,
       8.13272000e+03, 5.28480000e+02, 7.67290000e+02, 4.98600000e+01,
       3.24000000e+00, 2.53086019e+07, 2.38776659e+06, 1.55161728e+05,
       2.25276344e+05, 1.46388960e+04, 9.51264000e+02, 2.12539330e+04,
       1.38112200e+03, 8.97480000e+01, 5.83200000e+00])

In [22]:
X_train_scaled[0]

array([ 1.66759336,  0.26512404, -1.39553662,  2.20150373,  1.27757026,
       -0.90502331, -0.02131602, -0.8758223 , -0.83990056,  2.64499976,
        1.82073249, -0.65010896,  0.65667204, -0.64142146, -0.61276841,
       -0.23015661, -0.7133113 , -0.65028766, -0.56911778])

In [23]:
X_test_scaled[0]

array([ 0.0820634 ,  0.53029883,  1.08147034, -0.18419706,  0.39206466,
        0.76452278,  0.29694575,  0.95294897,  0.88878097, -0.36231576,
        0.06964412,  0.31408189,  0.2400246 ,  0.71721997,  0.61884939,
        0.07699863,  0.61811758,  0.76981675,  0.58139957])

Ridge - Regression

In [24]:
from sklearn.linear_model import Ridge

In [25]:
#help(Ridge)

In [26]:
ridge_model = Ridge(alpha = 10)

In [27]:
ridge_model.fit(X_train_scaled, y_train)

Ridge(alpha=10)

In [28]:
test_predections = ridge_model.predict(X_test_scaled)

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [30]:
MAE = mean_absolute_error(y_test, test_predections)

In [31]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predections))

In [32]:
MAE

0.6329556348463365

In [33]:
RMSE

0.8927190051123457

In [34]:
from sklearn.linear_model import RidgeCV

In [35]:
#help(RidgeCV)

In [36]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0))

In [37]:
ridge_cv_model.fit(X_train_scaled, y_train)

RidgeCV()

In [38]:
ridge_cv_model.alpha_

0.1

In [39]:
from sklearn.metrics import SCORERS

In [40]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

In [41]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring ='neg_mean_squared_error')

In [42]:
ridge_cv_model.fit(X_train_scaled, y_train)

RidgeCV(scoring='neg_mean_squared_error')

In [43]:
ridge_cv_model.alpha_

0.1

In [44]:
test_predection_cv = ridge_cv_model.predict(X_test_scaled)

In [45]:
MAE = mean_absolute_error(y_test, test_predection_cv)

In [46]:
MAE

0.4343075766486241

In [47]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predection_cv))

In [48]:
RMSE

0.5635899169556714

In [49]:
ridge_cv_model.coef_

array([ 5.84681185,  0.52142086,  0.71689997, -6.17948738,  3.75034058,
       -1.36283352, -0.08571128,  0.08322815, -0.34893776,  2.16952446,
       -0.47840838,  0.68527348,  0.63080799, -0.5950065 ,  0.61661989,
       -0.31335495,  0.36499629,  0.03328145, -0.13652471])

LASSO Regression

In [50]:
from sklearn.linear_model import Lasso, LassoCV

In [51]:
help(LassoCV)

Help on class LassoCV in module sklearn.linear_model._coordinate_descent:

class LassoCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  LassoCV(*, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, precompute='auto', max_iter=1000, tol=0.0001, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Lasso linear model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  The best model is selected by cross-validation.
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  eps : float, default=1e-3
 |      Length of the path. ``eps=1e-3`` means that
 |      ``alpha_min / alpha_max = 1e-3``.
 |  
 |  n_alphas : int, default=100
 |      Number of alphas along the regularization path.
 |  
 |  alp

In [52]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv = 5)

In [53]:
lasso_cv_model.fit(X_train_scaled, y_train)

LassoCV(cv=5, eps=0.1)

In [54]:
lasso_cv_model.alpha_

0.4968802520343365

In [55]:
test_predict_lasso = lasso_cv_model.predict(X_test_scaled)

In [56]:
MAE = mean_absolute_error(y_test, test_predict_lasso)

In [57]:
MAE

0.6791873341672893

In [58]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predict_lasso))

In [59]:
RMSE

1.0399114953979072

In [61]:
lasso_cv_model.coef_

array([0.96745344, 0.        , 0.        , 0.        , 3.84280259,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [62]:
from sklearn.linear_model import ElasticNetCV

In [76]:
elastic_model_cv = ElasticNetCV(l1_ratio = [.1, .5, .7, .9, .95, .99, 1], eps = 0.001, n_alphas = 100, max_iter = 1000000)

In [77]:
#help(ElasticNetCV)

In [83]:
elastic_model_cv.fit(X_train_scaled, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [84]:
elastic_model_cv.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [85]:
elastic_model_cv.l1_ratio_

1.0

In [86]:
elastic_model_cv.alphas

In [87]:
elastic_model_cv.alpha_

0.004968802520343366

In [88]:
lasso_cv_model.alpha_

0.4968802520343365

In [89]:
test_elastic_predict = elastic_model_cv.predict(X_test_scaled)

In [90]:
MAS = mean_absolute_error(y_test, test_elastic_predict)

In [92]:
RMSE = np.sqrt(mean_squared_error(y_test, test_elastic_predict))

In [93]:
MAE

0.6791873341672893

In [94]:
RMSE

0.5785146895301977